# A sample Gemfile
source "http://eu.yarp.io"

group :development do
  gem 'chef-zero'
  gem 'chef', '<= 11.6.2'
  gem 'berkshelf', '< 2.0.0'
  gem 'json', '<= 1.7.7'
  gem 'pry'
  gem 'pry-remote'
  gem 'pry-nav'
end
